spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://37.205.12.245:9443/realms/linup
        registration:
          oidc:
            client-id: web_app
            client-secret: web_app
            scope: openid, profile, email, offline_access